// console.log(
//   utils.isArray([]),
//   utils.isArray(null),
//   utils.isArrayNonEmpty([1, 2, 3]),
//   utils.isArrayNonEmpty([]),
//   utils.isArrayNonEmpty("hello"),
//   utils.isArrayOrString([1, 2, 3]),
//   utils.isArrayOrString("hello"),
//   utils.isArrayOrString(123),
//   utils.isBase64("SGVsbG8gV29ybGQ="),
//   utils.isBase64("SGVsbG8tV29ybGQ"),
//   utils.isBase64(""),
//   utils.isBase64("SGVsbG8!"),
//   utils.isBase64(123),
//   utils.isBoolean(false),
//   utils.isBoolean(null),
//   utils.isBooleanNumber(1),
//   utils.isBooleanNumber(0),
//   utils.isBooleanNumber(2),
//   utils.isBooleanNumber(true),
//   utils.isBooleanString("true"),
//   utils.isBooleanString("false"),
//   utils.isBooleanString("yes"),
//   utils.isBooleanString(true),
//   utils.isBooleanAny(true),
//   utils.isBooleanAny(1),
//   utils.isBooleanAny("false"),
//   utils.isBooleanAny(2),
//   utils.isBooleanAny("yes"),
//   utils.isCreditCardNumber("4532015112830366"),
//   utils.isCreditCardNumber("4532-0151-1283-0366"),
//   utils.isCreditCardNumber("1234567890123456"),
//   utils.isCreditCardNumber("123"),
//   utils.isCreditCardNumber(1234),
//   utils.isDate(new Date()),
//   utils.isDate("2024-01-01"),
//   utils.isDate(1704067200000),
//   utils.isDate(new Date("invalid")),
//   utils.isDate("not a date"),
//   utils.isDate(null),
//   utils.isEmail("user@example.com"),
//   utils.isEmail("user@sub.domain.co"),
//   utils.isEmail("@example.com"),
//   utils.isEmail("user@"),
//   utils.isEmail("user@domain"),
//   utils.isEmail("user@domain."),
//   utils.isEmail("notanemail"),
//   utils.isEmail(123),
//   utils.isEnvNode,
//   utils.isEnvWindow,
//   utils.isEnvDocument,
//   utils.isEnvBrowser,
//   utils.isEnvWorker,
//   utils.nodeEnv,
//   utils.isEnvDevelopment,
//   utils.isEnvProduction,
//   utils.isEnvStaging,
//   utils.isEnvTest,
//   utils.isEnvLive,
//   utils.isEnvWindowProperty,
//   utils.isEnvLocalhost,
//   utils.isEnvServiceWorker,
//   utils.isEnvNotificationGranted,
//   utils.isError(new Error("oops")),
//   utils.isError(new TypeError("oops")),
//   utils.isError({ message: "oops" }),
//   utils.isError("oops"),
//   utils.isError(null),
//   utils.isFunction(() => {}),
//   utils.isFunction(function () {}),
//   utils.isFunction(class Foo {}),
//   utils.isFunction("hello"),
//   utils.isFunction(null),
//   utils.isHTTP("https://example.com"),
//   utils.isHTTP("http://example.com"),
//   utils.isHTTP("HTTP://example.com"),
//   utils.isHTTP("ftp://example.com"),
//   utils.isHTTP("example.com"),
//   utils.isHTTP(123),
//   utils.isJSON({ a: 1 }),
//   utils.isJSON([1, 2, 3]),
//   utils.isJSON("hello"),
//   utils.isJSON(undefined),
//   utils.isJSON(() => {}),
//   utils.isJSONString('{"a":1}'),
//   utils.isJSONString("[1, 2, 3]"),
//   utils.isJSONString('"hello"'),
//   utils.isJSONString("undefined"),
//   utils.isJSONString("{a: 1}"),
//   utils.isJSONString(123),
//   utils.isJWT(utils.jwt.encode({ id: 1 })),
//   utils.isJWT("not-a-jwt"),
//   utils.isJWT(""),
//   utils.isJWT(123),
//   utils.isModule("fs"),
//   utils.isModule("express"),
//   utils.isModule("nonexistent"),
//   utils.isModule(123),
//   utils.isNumber(123),
//   utils.isNumber(NaN),
//   utils.isNumber(Infinity),
//   utils.isNumber("123"),
//   utils.isNumber(null),
//   utils.isNumberString("123"),
//   utils.isNumberString("12.3"),
//   utils.isNumberString(""),
//   utils.isNumberString("abc"),
//   utils.isNumberString(123),
//   utils.isNumberValid(123),
//   utils.isNumberValid(NaN),
//   utils.isNumberValid(Infinity),
//   utils.isNumberValid("123"),
//   utils.isNumeric(123),
//   utils.isNumeric("123"),
//   utils.isNumeric("12.3"),
//   utils.isNumeric(NaN),
//   utils.isNumeric(""),
//   utils.isNumeric("abc"),
//   utils.isObject({}),
//   utils.isObject({ a: 1 }),
//   utils.isObject(Object.create(null)),
//   utils.isObject([]),
//   utils.isObject(new Map()),
//   utils.isObject(null),
//   utils.isObject(123),
//   utils.isObjectNonEmpty({ a: 1 }),
//   utils.isObjectNonEmpty({}),
//   utils.isObjectNonEmpty([]),
//   utils.isObjectNonEmpty(null),
//   utils.isPhoneNumber("+14155552671"),
//   utils.isPhoneNumber("14155552671"),
//   utils.isPhoneNumber("+441234567890"),
//   utils.isPhoneNumber("0044123456"),
//   utils.isPhoneNumber("+1"),
//   utils.isPhoneNumber("123 456 7890"),
//   utils.isPhoneNumber(123),
//   utils.isRegex(/hello/),
//   utils.isRegex(new RegExp("hi")),
//   utils.isRegex("hello"),
//   utils.isRegex(null),
//   utils.isString(""),
//   utils.isString(null),
//   utils.isStringNonEmpty("hello"),
//   utils.isStringNonEmpty("  "),
//   utils.isStringNonEmpty(""),
//   utils.isStringNonEmpty(123),
//   utils.isStringSafeRegex("hello"),
//   utils.isStringSafeRegex("(a+)+"),
//   utils.isStringSafeRegex(123),
//   utils.isURL(new URL("https://example.com")),
//   utils.isURL("https://example.com"),
//   utils.isURL(null),
//   utils.isURLString("https://example.com"),
//   utils.isURLString("http://localhost:3000"),
//   utils.isURLString("example.com"),
//   utils.isURLString("not a url"),
//   utils.isURLString(""),
//   utils.isURLString(123),
//   utils.isValid(0),
//   utils.isValid(""),
//   utils.isValid(null),
//   utils.isValid(undefined),
//   utils.isValid("", true),
//   utils.isValid(NaN, true),
//   utils.isValid({}, true),
//   utils.isValid([], true),
// );
